import LocalizedStrings from "react-localization";
export const strings = new LocalizedStrings({
  en: {
    email_is_required: "Email is required",
    valid_email_msg: "Please enter a valid email",
    password_is_required: "Password is required",
    valid_password_min_msg: "Password must be more than 8 characters",
    valid_password_max_msg: "Password must be less than 32 characters",
    sign_in_to_us: "Sign in to us",
    username_or_email_address: "Username or email address",
    password: "Password",
    login: "Login",
    first_time: "First time",
    create_an_account: "Create an account",
    back_to_homepage: "Back to Homepage",
    login_reg_page: "login / register page",
    join_us_now: "join us now and don't waste time",
    register: "register",
    reset_your_password: "Reset your password",
    email_address: "Email address",
    send_pwd_msg: "Send password reset email",
    welcome_user: "welcome user",
    log_out: "Log out",
    join_us: "Join us",
    create_your_account: "Create your personal account",
    username: "Username",
    i_agree_statement: "I agree all statements in",
    user_name_is_required: "User Name is required",
    terms_of_services_is_required: "Please accept the terms of services",
    login_to_your_account: "Please enter your details to log in.",
    forget_password: "Forgot Password?",
    email: "Email",
    loading: "Loading...",
    please_wait: "Please wait",
    notification: "Notification",
    back: " Back",
    brain_Gym: "Brain Gym",
    founded_on: "  Founded on",
    address: " Address",
    number_of_employees: "Number of employees",
    description: "Description",
    dashboard: "Dashboard",
    profile: "Profile",
    logout: "Logout",
    customer_support: "Customer Support",
    gender: "Gender",
    primary_language: "Primary Language",
    secondary_language: "Secondary Language",
    country: "Country",
    state: "State",
    city: "City",
    pronouns: "Pronouns",
    about_me: "About me",
    forgot_password: "Forgot Password",
    forgot_password_message:
      "Enter an email address associated with your account so that we can send the OTP via email to reset your password. ",
    send_otp: "Send OTP",
    otp: "OTP",
    otp_message:
      "Enter the 4 digit OTP that has been sent on your registered email address. ",
    resend_otp: "Resend OTP",
    confirm: "Confirm",
    invalid_otp: "Invalid OTP.",
    reset_password: "Reset Password",
    reset_password_message:
      "Enter a new password below to reset your password.",
    set_password: "Set Password",
    confirm_password: "Confirm Password",
    password_error_message: "Wrong Password, please try again.",
    email_error: "Incorrect email, please try again.",
    password_success:
      "Congratulations! Your password has been reset successfully.",
    page_not_found: "Page Not Found",
    page_not_found_sorry_text: "Sorry, we were unable to find that page",
    go_back: "Go Back",
    total_users: "Total users",
    active: "Active",
    engaged: "Engaged",
    inactive: "Inactive",
    low_engagement: "Low Engagement",
    total_employees: "Total Employees",
    poor: "Poor",
    ok: "Ok",
    great: "Great",
    good: "Good",
    calls: "Calls",
    messages: "Messages",
    total_coaches: "Total Coaches",
    average: "Average",
    organizations_brain_health: "Organization’s Brain Health",
    brain_health: "Brain Health",
    stress: "Stress",
    well_being: "Well-Being",
    well_being_practices: "Well-Being Practices",
    employees_brain_score_range: "Current Brain Health Scores",
    affect_continuum: "Affect Continuum",
    sentiment: "Sentiment",
    emotionality: "Emotionality",
    most_shared_resources: "Most Shared Resources",
    most_added_events: "Most Added Events",
    view_details: "View details",
    messages_and_calls: "Messages and Calls",
    customer_service_headline:
      "Reach out to us by sending your queries and concerns about this application on the email ID given below.",
    password_do_not_match: '"The passwords did not match"',
    otp_is_required: "OTP is required",
    phone_number: "Phone Number",
    organization: "Organization",
    server_error_500: "Invalid request",
    server_error_405: "Invalid request",
    terms_of_services: "Terms Of Services",
    privacy_policy: "Privacy Policy",
    password_not_match_error:
      "The password and confirmation password do not match",
    uppercase_character_required: "One uppercase character is required",
    lowercase_character_required: "One lowercase character is required",
    number_required: "One number is required",
    special_character_required: "One special character is required",
    otp_send_success_msg: "OTP has been sent successfully.",
    server_error_401: "Session expired",
    server_error_404: "Invalid request",
    hello: "Hello",
    user_account: "User Account",
    current_sentiment: " Current Sentiment",
    current_emotions: "Current Emotions",
    emotional_state: "Emotional State",
    employees_brain_score_range_info:
      "Current Brain Health Scores for your employees, based on their most recent survey responses",
    overall_score: "Overall Score",
    current_emotions_tooltip:
      "Current emotions of your employees, based on sentiment analysis.",
    current_sentiment_tooltip:
      "Current dispositions of your employees, based on sentiment analysis.",
    emotional_state_tooltip:
      "Current affective states of your employees, based on sentiment analysis.",
    coach_rating: "Coach Rating",
    filter: "Filter",
    no_of_coach: "No. of Coach",
    manage_widgets: "Manage widgets",
    first_name_is_required: "First Name is required",
    gender_is_required: "Gender is required",
    last_name_is_required: "Last Name is required",
    department_is_required: "Department is required",
    position_is_required: "Position is required",
    sec_lang_is_required: "Second Language is required",
    about_me_is_required: "About me field is required",
    country_is_required: "Country is required",
    primary_language_is_required: "Language is required",
    pronouns_is_required: "Pronouns is required",
    state_is_required: "State is required",
    city_is_required: "City is required",
    profile_photo_text: "Profile photo",
    cancel: "Cancel",
    update: "Update",
    positive: "Positive",
    neutral: "Neutral",
    negative: "Negative",
    happy: "Happy",
    disappointed: "Disappointed",
    fearful: "Fearful",
    angry: "Angry",
    sad: "Sad",
    surprise: "Surprise",
    contempt: "Contempt",
    organization_brain_health: "Organization’s Brain Health",
    overall_brain_health_score: "Overall Brain Health Score",
    work_related_wellbeing_burnout: "Work-Related Wellbeing & Burnout",
    wellbeing_practices: "Wellbeing Practices",
    compare_domains: "Compare Domains",
    select_up_to: "Please select at least 2 domains to view the comparison chart. (Maximum domains selected can be 5)",
    domains: "Domains",
    brain_health_domains_comparison: "Brain Health Domains Comparison",
    burnout: "Burnout",
    anxiety: "Anxiety",
    energy: "Energy",
    contributors: "Contributors",
    contemplative_practices: "Contemplative Practices",
    select_domain: "Select Domain",
    update_profile_success_message:
      "You have successfully updated your profile.",
    error: "Error",
    logged_in_successfully: "You have successfully logged in",
    created_date_range: "Created Date Range",
    resource_type: "Resource Type",
    clear: "Clear",
    apply: "Apply",
    start_date: "Start Date",
    end_date: "End Date",
    department: "Department",
    location: "Location",
    date_range: "Date Range",
    current_brain_health_filter: "Current Brain Health Score Filter",
    current_emotions_filter: "Current Emotions Filter",
    current_sentiment_filter: "Current Sentiment Filter",
    emotion_state_filter: "Emotional State Filter",
    count: "Count",
    event_type: "Event type",
    organization_brain_health_filter: "Organization’s Brain Health Filter",
    domain_select_error: "you can select up to 5 domains",
    no_data_found_for_compare_domains: "No data found",
    no_domain_selected_msg:
      "No domain selected to compare. Please select domains.",
    detail_page: "Dashboard > Organization’s Brain Health",
    title: "Title",
    star: "Star",
    rating: "Rating",
    coach_rating_filter: "Coach Rating Filter",
    select: "Select",
    recurrence: "Recurrence",
    invalidDateMessage: "Start date should not be greater than end date",
    invalidStartDateMessage: "Please select start date first.",
    first_name_max_msg: "First name must be less than 100 characters",
    last_name_max_msg: "Last name must be less than 100 characters",
    department_max_msg: "Department must be less than 100 characters",
    sec_language_max_msg: "Secondary language must be less than 100 characters",
    position_max_msg: "Position must be less than 100 characters",
    about_me_max_msg: "About me must be less than 500 characters",
    gender_description_is_required: "Gender description is required",
    pronouns_description_is_required: "Pronouns description is required",
    gender_description_max_msg: "Gender description must be less than 100 characters",
    pronouns_description_max_msg: "Pronouns description must be less than 100 characters",
    pronouns_description: "Pronouns Description",
    gender_description: "Gender Description",
    summary: "Summary",
    sentiment_analysis: "Sentiment Analysis",
    coach: "Coach",
    events_and_external_resources: 'Events and External Resources',
    edit_profile: "Edit Profile"
  },
  fr: {
    email_is_required: "L'e-mail est requis",
    valid_email_msg: "Veuillez entrer un email valide",
    password_is_required: "Mot de passe requis",
    valid_password_min_msg: "Password must be more than 8 characters",
    valid_password_max_msg: "Password must be less than 32 characters",
    sign_in_to_us: "Connectez-vous",
    username_or_email_address: "Nom d'utilisateur ou adresse e-mail",
    password: "Mot de passe",
    forget_password: "Mot de passe oublié",
    login: "Connexion",
    first_time: "Première fois",
    create_an_account: "Créer un compte",
    back_to_homepage: "Retour à la page d'accueil",
    organization: "Organization",
    phone_number: "Phone number",
    total_users: "Total users",
    active: "Active",
    engaged: "Engaged",
    inactive: "Inactive",
    low_engagement: "Low Engagement",
    total_employees: "Total Employees",
    poor: "Poor",
    ok: "Ok",
    great: "Great",
    good: "Good",
    calls: "Calls",
    messages: "Messages",
    total_coaches: "Total Coaches",
    average: "Average",
    organizations_brain_health: "Organization’s Brain Health",
    most_shared_resources: "Most Shared Resources",
    most_added_events: "Most Shared Resources",
    messages_and_calls: "Messages and Calls",
    overall_score: "Overall Score",
  },
});
// This is to update language, default will be first one
//strings.setLanguage('fr');
